hl.on("hyprland.start", function()
	hl.exec_cmd("uwsm app -- theme-apply --cached")
	hl.exec_cmd("uwsm app -- nm-applet --indicator")
	hl.exec_cmd("uwsm app -- polkit-gnome-authentication-agent-1")
	hl.exec_cmd("uwsm app -- udiskie --tray")
	hl.exec_cmd("uwsm app -- quickshell")
	hl.exec_cmd("uwsm app -- hypridle")
	hl.exec_cmd("uwsm app -- wayscriber --daemon")
	hl.exec_cmd("uwsm app -- wallpaper-set --restore")
end)

hl.env("XCURSOR_THEME", "Vimix-cursors")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("GDK_BACKEND", "wayland,x11")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
