general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 20 min sin actividad: bloquear pantalla.
listener {
    timeout = 1200
    on-timeout = loginctl lock-session
}

# 30 min sin actividad: apagar pantalla.
listener {
    timeout = 1800
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 40 min sin actividad: suspender.
listener {
    timeout = 2400
    on-timeout = systemctl suspend
}
